//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 批量修改图片.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SettingsOldFilePath {
            get {
                return ((string)(this["SettingsOldFilePath"]));
            }
            set {
                this["SettingsOldFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SettingsNewFilePath {
            get {
                return ((string)(this["SettingsNewFilePath"]));
            }
            set {
                this["SettingsNewFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("230, 28, 28")]
        public global::System.Drawing.Color SettingsOldColor {
            get {
                return ((global::System.Drawing.Color)(this["SettingsOldColor"]));
            }
            set {
                this["SettingsOldColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("77, 216, 99")]
        public global::System.Drawing.Color SettingsNewColor {
            get {
                return ((global::System.Drawing.Color)(this["SettingsNewColor"]));
            }
            set {
                this["SettingsNewColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public decimal SettingsSimilarity {
            get {
                return ((decimal)(this["SettingsSimilarity"]));
            }
            set {
                this["SettingsSimilarity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingIsSingleValue {
            get {
                return ((bool)(this["SettingIsSingleValue"]));
            }
            set {
                this["SettingIsSingleValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingIsFilterCheck {
            get {
                return ((bool)(this["SettingIsFilterCheck"]));
            }
            set {
                this["SettingIsFilterCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection SettingFilterListView {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SettingFilterListView"]));
            }
            set {
                this["SettingFilterListView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingsOldColorCheckBox1 {
            get {
                return ((bool)(this["SettingsOldColorCheckBox1"]));
            }
            set {
                this["SettingsOldColorCheckBox1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingsOldColorCheckBox2 {
            get {
                return ((bool)(this["SettingsOldColorCheckBox2"]));
            }
            set {
                this["SettingsOldColorCheckBox2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingsOldColorCheckBox3 {
            get {
                return ((bool)(this["SettingsOldColorCheckBox3"]));
            }
            set {
                this["SettingsOldColorCheckBox3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingsOldColorCheckBox4 {
            get {
                return ((bool)(this["SettingsOldColorCheckBox4"]));
            }
            set {
                this["SettingsOldColorCheckBox4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingsOldColorCheckBox5 {
            get {
                return ((bool)(this["SettingsOldColorCheckBox5"]));
            }
            set {
                this["SettingsOldColorCheckBox5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("230, 28, 28")]
        public global::System.Drawing.Color SettingsOldColorShow1 {
            get {
                return ((global::System.Drawing.Color)(this["SettingsOldColorShow1"]));
            }
            set {
                this["SettingsOldColorShow1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("230, 28, 28")]
        public global::System.Drawing.Color SettingsOldColorShow2 {
            get {
                return ((global::System.Drawing.Color)(this["SettingsOldColorShow2"]));
            }
            set {
                this["SettingsOldColorShow2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("230, 28, 28")]
        public global::System.Drawing.Color SettingsOldColorShow3 {
            get {
                return ((global::System.Drawing.Color)(this["SettingsOldColorShow3"]));
            }
            set {
                this["SettingsOldColorShow3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("230, 28, 28")]
        public global::System.Drawing.Color SettingsOldColorShow4 {
            get {
                return ((global::System.Drawing.Color)(this["SettingsOldColorShow4"]));
            }
            set {
                this["SettingsOldColorShow4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("230, 28, 28")]
        public global::System.Drawing.Color SettingsOldColorShow5 {
            get {
                return ((global::System.Drawing.Color)(this["SettingsOldColorShow5"]));
            }
            set {
                this["SettingsOldColorShow5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SettingsPassword {
            get {
                return ((string)(this["SettingsPassword"]));
            }
            set {
                this["SettingsPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingsDeveloperModel {
            get {
                return ((bool)(this["SettingsDeveloperModel"]));
            }
            set {
                this["SettingsDeveloperModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DevNewTestModel {
            get {
                return ((bool)(this["DevNewTestModel"]));
            }
            set {
                this["DevNewTestModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DevOtherModel {
            get {
                return ((bool)(this["DevOtherModel"]));
            }
            set {
                this["DevOtherModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection DevOtherResizeList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DevOtherResizeList"]));
            }
            set {
                this["DevOtherResizeList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DevOtherResizeRadioButton {
            get {
                return ((bool)(this["DevOtherResizeRadioButton"]));
            }
            set {
                this["DevOtherResizeRadioButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DevOtherResizeCutRadioButton {
            get {
                return ((bool)(this["DevOtherResizeCutRadioButton"]));
            }
            set {
                this["DevOtherResizeCutRadioButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DevOtherSavePicFormatCheckBox {
            get {
                return ((bool)(this["DevOtherSavePicFormatCheckBox"]));
            }
            set {
                this["DevOtherSavePicFormatCheckBox"] = value;
            }
        }
        
        /// <summary>
        /// 比例模式所以尺寸
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("比例模式所以尺寸")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection DevOtherScaleAddListBox {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DevOtherScaleAddListBox"]));
            }
            set {
                this["DevOtherScaleAddListBox"] = value;
            }
        }
        
        /// <summary>
        /// 当前资源分辨率宽度
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("当前资源分辨率宽度")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1920")]
        public string DevOtherScaleWidthTextBox {
            get {
                return ((string)(this["DevOtherScaleWidthTextBox"]));
            }
            set {
                this["DevOtherScaleWidthTextBox"] = value;
            }
        }
        
        /// <summary>
        /// 当前资源分辨率高度
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("当前资源分辨率高度")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1080")]
        public string DevOtherScaleHeightTextBox {
            get {
                return ((string)(this["DevOtherScaleHeightTextBox"]));
            }
            set {
                this["DevOtherScaleHeightTextBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingsNewColorCheckBox1 {
            get {
                return ((bool)(this["SettingsNewColorCheckBox1"]));
            }
            set {
                this["SettingsNewColorCheckBox1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fuchsia")]
        public global::System.Drawing.Color SettingsNewColorShow1 {
            get {
                return ((global::System.Drawing.Color)(this["SettingsNewColorShow1"]));
            }
            set {
                this["SettingsNewColorShow1"] = value;
            }
        }
    }
}
